### ISSUE TITLE
totally useless

### ISSUE THREAD

**Issue by ZERO-2020** [BinCT/Calamity-Injector#1]
does not boot at all

**Comment by MBR07** [comment]
its a trojan

**Comment by MBR07** [comment]
https://www.virustotal.com/gui/file/628e1374d0ea97696da6b51b6d600a490cb260c2bf4bbaeb6cef9911f1f99fbb/detection

**Comment by MBR07** [comment]
get an antivirus asap

**Comment by BinCT** [comment]
> does not boot at all

If it doesn't boot then you are missing the required API that I included. I plan to update the tool and also make it open source.
