### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by MBR07** [BinCT/Calamity-Injector#2]
https://www.virustotal.com/gui/file/628e1374d0ea97696da6b51b6d600a490cb260c2bf4bbaeb6cef9911f1f99fbb/detection

Remove it. You are a piece of crap. Stop infecting random people.

**Comment by MBR07** [comment]
Make it open source.

**Comment by BinCT** [comment]
> https://www.virustotal.com/gui/file/628e1374d0ea97696da6b51b6d600a490cb260c2bf4bbaeb6cef9911f1f99fbb/detection
> 
> Remove it. You are a piece of crap. Stop infecting random people.

You don't seem very used to tools then, no. I did not create malware. I made this tool for personal use, actually. I use it and I do not get infected ever. But. I will say that I don't entirely trust the creators of the API. Then again. I decompiled the API and saw that it has nothing malicious. So no, this will not infect you. You can even decompile my tool and the API if you wish. To do so I recommend DnsSpy. The tool is written in C# so you could just convert it back into a project folder for Visual Studio.
