### ISSUE TITLE
Please Help?

### ISSUE THREAD

**Issue by EatsThatBraile** [BinCT/Calamity-Injector#3]
1. How do I open up the Injector??? its a .dll file. So how do i run the injector???
2. How would i put scripts into it.

I would be very thankful if you could give me an answer.

**Comment by BinCT** [comment]
Kind of debating on completely abandoning the project. Anyway that's not the point.

> The tool has been removed due to API errors and updating. The tool will be re-released soon.

It's not for use right now, I might rerelease it for people to use soon.
